status = [
  "buildkite/tbco-monitoring-framework",
  "ci/hydra:Bcc:tbco-monitoring:required",
]
timeout_sec = 7200
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
use_squash_merge = false
