#TODO update ghc-versions, and bcc-network name  
  # GHC 8.6.5
resolver: lts-14.27
compiler: ghc-8.6.5

  # GHC 8.10.2
#resolver: nightly-2020-08-26
#compiler: ghc-8.10.2

packages:
  - contra-tracer
  - tracer-transformers
  - tbco-monitoring
  - plugins/backend-aggregation
  - plugins/backend-editor
  - plugins/backend-ekg
  - plugins/backend-graylog
  - plugins/backend-monitoring
  - plugins/backend-trace-acceptor
  - plugins/backend-trace-forwarder
  - plugins/scribe-systemd
  - examples

allow-newer: false

extra-deps:
  # needed for GHC 8.10.2
  #- async-timer-0.2.0.0
  - network-3.1.1.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1

  - time-units-1.0.0
  - katip-0.8.4.0

  - git: https://github.com/The-Blockchain-Company/bcc-network
    commit: a09f209bb6bbb1a1a9a5b31d671da0189001e175
    subdirs:
        - Win32-network

  - git: https://github.com/CodiePP/libsystemd-journal
    commit: 49ad111e668e0d6e06e759a13d8de311bc91e149
    subdirs:
        - .

nix:
  pure: false
#  shell-file: nix/stack-shell.nix
  packages: [ zlib.dev, zlib.out
            , openssl.dev, openssl.out
            , libsodium.dev, libsodium.out
            , haskell.compiler.ghc8102
            , pkg-config
            , systemd.dev
            ]

